### ISSUE TITLE
API stuff (Required for infoedu)

### ISSUE THREAD

**Issue by BrandonHowe** [Vyctor661/king-typer#34]
- [x] delete users
- [x] edit users
- [x] get all users
- [x] delete text/tutorial #30 
- [x] edit text/tutorial #30 
- [x] add text/tutorial #30 
- [x] get all texts
- [x] add achievements
- [x] edit achievements 
- [x] delete achievements 
- [x] get all achievements 
- [x] multiplayer stuff #26
